// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RickAndMorty.Migrations
{
    [DbContext(typeof(UploadHistoryContext))]
    [Migration("20250808171723_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CharacterEpisodeModel", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "EpisodeId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("CharacterEpisode");
                });

            modelBuilder.Entity("CharacterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("EpisodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Episode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDataModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileDataModelId");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("FileDataEpisodeModel", b =>
                {
                    b.Property<string>("FileDataId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileDataId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("FileDataId");

                    b.ToTable("FileDataEpisode");
                });

            modelBuilder.Entity("FileDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFemaleCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGenderUnknownCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGenderlessCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLocations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMaleCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadeFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileData");
                });

            modelBuilder.Entity("LocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("ReceivedFile.Model.ReceivedFileModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UploadHistory");
                });

            modelBuilder.Entity("CharacterEpisodeModel", b =>
                {
                    b.HasOne("CharacterModel", "Character")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EpisodeModel", "Episode")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("CharacterModel", b =>
                {
                    b.HasOne("LocationModel", "Location")
                        .WithMany("AsLocationFor")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocationModel", "Origin")
                        .WithMany("AsOriginFor")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("EpisodeModel", b =>
                {
                    b.HasOne("FileDataModel", null)
                        .WithMany("Episodes")
                        .HasForeignKey("FileDataModelId");
                });

            modelBuilder.Entity("FileDataEpisodeModel", b =>
                {
                    b.HasOne("EpisodeModel", "Episode")
                        .WithMany("FileDataEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileDataModel", "FileData")
                        .WithMany("FileDataEpisodes")
                        .HasForeignKey("FileDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("FileData");
                });

            modelBuilder.Entity("CharacterModel", b =>
                {
                    b.Navigation("CharacterEpisodes");
                });

            modelBuilder.Entity("EpisodeModel", b =>
                {
                    b.Navigation("CharacterEpisodes");

                    b.Navigation("FileDataEpisodes");
                });

            modelBuilder.Entity("FileDataModel", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("FileDataEpisodes");
                });

            modelBuilder.Entity("LocationModel", b =>
                {
                    b.Navigation("AsLocationFor");

                    b.Navigation("AsOriginFor");
                });
#pragma warning restore 612, 618
        }
    }
}
